---
output: 
  html_document:
    code_folding: hide
css: styles.css
---
  
# Evaluation of oyster calcification {.tabset}
  
```{r setup, message = F, warning = F, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(readxl)
library(patchwork)
library(ggbeeswarm)
library(psycho)
library(lmerTest)
library(hrbrthemes)
library(kableExtra)
library(shiny)
library(janitor)
library(patchwork)
library(modelbased)

source('R/funcs.R')

calcdat <- read_excel('data/raw/Prism_average (3).xlsx') %>% 
  clean_names() %>% 
  filter(week != 0) %>% 
  select(
    species, 
    week, 
    trt = treatment,
    val = avg_prisms
  ) %>%
  mutate(
    trt = factor(trt, levels = c("7.7C", "7.7A0.2", "7.7A0.5", "8.0C", "8.0A0.2"))
  )

# treatment colors
cls <- RColorBrewer::brewer.pal(6, 'BrBG')
cls <- c(cls[1:3], cls[c(6, 4)])
names(cls) <- levels(calcdat$trt)

# fit separate mixed models by species, week not tested
bymods <- calcdat %>%
  group_by(species) %>% 
  nest %>% 
  mutate(
    mixmod = pmap(list(data), function(data){
      
      tomod <- data %>%
        mutate(
          trt = fct_drop(trt)
        )
      
      out <- lm(val ~ trt, data = tomod)
      
      return(out)
      
    }),
    anomod = map(mixmod, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    plomod = pmap(list(species, mixmod), function(species, mixmod){

      # estimates
      mnsval <- estimate_means(mixmod, 'trt')
      cnsval <- estimate_contrasts(mixmod, 'trt') %>% 
        mutate(
          sig = ifelse(p < 0.05, 'sig', 'notsig'),
          sig = factor(sig,levels = c('notsig', 'sig'), labels = c(' not significant', 'significant'))
        ) %>% 
        unite('Contrast', Level1, Level2, sep = '-')
      
      # sample size
      n <- nrow(model.frame(mixmod))
      
      # labels
      subttl <- paste0(species, ' oyster')
      captns <- paste0('Significance is where CI does not include zero, alpha = 0.05, total n = ', n)
      
      # mean esimate plots
      p1 <- ggplot(mnsval, aes(x = trt, y = Mean)) + 
        geom_point(size = 3) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high), colour = 'black', size = 1) + 
        labs(x = NULL, y = 'Estimated means (+/- 95% CI)', title = 'Treatment estimates', subtitle = subttl) + 
        theme_ipsum() + 
        theme(
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()
        ) + 
        coord_flip()
      
      # contrast plots
      p2 <- ggplot(cnsval, aes(x = Contrast, y = Difference, colour = sig)) + 
        geom_point(aes(colour = sig), size = 3) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high, colour = sig), size = 1) + 
        labs(x = NULL, y = 'Estimated differences (+/- 95% CI)', title = 'Treatment differences', subtitle = subttl,
             caption = captns) +
        theme_ipsum() + 
        theme(
          legend.title = element_blank(), 
          legend.position = 'bottom', 
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()
        ) +
        geom_hline(yintercept = 0, linetype = 'dotted', size = 1) + 
        scale_colour_manual(drop = F, values = c('black', 'tomato1')) + 
        coord_flip()
      
      p1 + p2 + plot_layout(ncol  = 2)   
      
      
    })
  )

# all comparisons
calcmodsall <- calcdat %>%
  group_by(species) %>% 
  nest %>% 
  mutate(
    mixmodnoint = purrr::map(data, function(x){
      
      tomod <- x %>% 
        mutate(
          week = factor(week), 
          trt = fct_drop(trt)
        )
      
      out <- lm(val ~ trt + week, data = tomod)
      
      return(out)
      
    }),
    anomodnoint = purrr::map(mixmodnoint, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    plomod = purrr::pmap(list(species, mixmodnoint), function(species, mixmodnoint){
      
      # estimates
      mnsval <- estimate_means(mixmodnoint)

      # sample size
      n <- nrow(model.frame(mixmodnoint))
      
      # labels
      subttl <- paste0('Calcification, ', species, ' oyster')
      captns <- paste0('Significance is where CI does not include zero, alpha = 0.05, total n = ', n)
      
      # mean esimate plots
      p1 <- ggplot(mnsval, aes(x = week, y = Mean, group = trt, colour = trt, fill = trt)) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high, colour = trt), width = 0, position = position_dodge(0.3), size = 1) + 
        geom_line(position = position_dodge(0.3)) + 
        geom_point(size = 3, position = position_dodge(0.3), pch = 21, colour = 'black') + 
        labs(x = 'Exposure week', y = 'Estimated means (+/- 95% CI)', title = 'Treatment estimates', subtitle = subttl, caption = captns) + 
        scale_colour_manual(values = cls) + 
        scale_fill_manual(values = cls) + 
        theme_ipsum() + 
        theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          legend.title = element_blank()
        )
      
      p1
      
    })
  )

```

## Treatment effects only, all weeks combined {.tabset .tabset-pills}

### Olympia oyster

```{r, fig.height = 5, fig.width = 10, out.width = '90%', results = 'hide'}
bymods %>% filter(species == 'Olympia') %>% pull(plomod)
```

### Pacific oyster

```{r, fig.height = 5, fig.width = 10, out.width = '90%', results = 'hide'}
bymods %>% filter(species == 'Pacific') %>% pull(plomod)
```

## All treatments {.tabset .tabset-pills}

### Olympia oyster

```{r}
dat <- calcmodsall %>% 
  filter(species == 'Olympia')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Calcification vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

### Pacific oyster

```{r}
dat <- calcmodsall %>% 
  filter(species == 'Pacific')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Calcification vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

### Species together

```{r}
mixmodnoint <- lm(val ~ trt + week + species, data = calcdat)
anomodnoint <- anova(mixmodnoint)

anomodnoint %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Calcification vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```
