---
title: "Puget Sound observed pH time series detiding: Pt 2"
author: "M. W. Beck"
output: html_document
---
  
```{r setup, warning = F, message = F}
library(knitr)
library(tidyverse)
library(readxl)
library(here)
library(lubridate)
library(janitor)
library(mgcv)

opts_chunk$set(warning = FALSE, message = FALSE)

# buoy, farm WDNR
obsdat1 <- read.csv(here('data/raw/2018 WDNR pH sensor data - 2018 WDNR pH sensor data.csv.csv')) %>% 
  select(Date, TimePST, BuoypHAG, MidpHP1) %>% 
  gather('loc', 'pH', -Date, -TimePST) %>% 
  mutate(
    loc = case_when(
      grepl('Buoy', loc) ~ 'WDNR Buoy', 
      grepl('Mid', loc) ~ 'WDNR Farm center'
    ), 
    loc = factor(loc, levels = c('WDNR Buoy', 'WDNR Farm edge', 'WDNR Farm center'))
  ) %>% 
  unite('datetime', Date, TimePST, sep = ' ') %>% 
  mutate(
    datetime = mdy_hms(datetime, tz = 'Pacific/Pitcairn')
  ) %>% 
  filter(as.Date(datetime) <= ymd('2018-07-07') & as.Date(datetime) >= ymd('2018-05-25')) %>% 
  filter(minute(datetime) == 0)

subdts <- ymd(c('2018-05-25', '2018-07-06'))

# SB1 1m
obsdat2 <- read.csv(here('data/raw/SB1_1m_PMEL_2017-2018.csv')) %>% 
  group_by(year, month, day, hour) %>% 
  sample_n(1) %>% # sometimes there's more than one measurement per hour
  ungroup %>% 
  unite('date', month, day, year, sep = '-') %>% 
  unite('time', hour, min, sec, sep = ':') %>% 
  unite('datetime', date, time, sep = ' ') %>% 
  mutate(
    datetime = mdy_hms(datetime, tz = 'UTC'), 
    datetime = with_tz(datetime, tz = 'Pacific/Pitcairn'),
    datetime = floor_date(datetime, unit = 'hour'),
    loc = 'SB1 1m'
  ) %>% 
  rename(pH = pH_tot) %>% 
  filter(as.Date(datetime) <= subdts[2] & as.Date(datetime) >= subdts[1])

# NB1 3m
obsdat3 <- read.csv(here('data/raw/NB1_3m_SeaFET001_pH_tot.csv')) %>% 
  group_by(year, month, day, hour) %>% 
  sample_n(1) %>% # sometimes there's more than one measurement per hour
  ungroup %>% 
  unite('date', month, day, year, sep = '-') %>% 
  unite('time', hour, min, sec, sep = ':') %>% 
  unite('datetime', date, time, sep = ' ') %>% 
  mutate(
    datetime = mdy_hms(datetime, tz = 'UTC'), 
    datetime = with_tz(datetime, tz = 'Pacific/Pitcairn'),
    datetime = floor_date(datetime, unit = 'hour'),
    loc = 'NB1 3m'
  ) %>% 
  rename(pH = pH_tot) %>% 
  filter(as.Date(datetime) <= subdts[2] & as.Date(datetime) >= subdts[1])

# combine
obsdat <- bind_rows(obsdat1, obsdat2, obsdat3)

# tidal data from ADCP
tiddat <- read.csv(here('data/raw/SL1_Lander_depth_UTC.csv')) %>%
  unite('datetime', year, month, day, hour, min, sec) %>% 
  # clean_names() %>%
  rename( 
    Tide = depth
  ) %>% 
  mutate(
    datetime = ymd_hms(datetime), 
    datetime = with_tz(datetime, tzone = 'Pacific/Pitcairn')
  ) %>% 
  filter(minute(datetime) == 0 & second(datetime) == 0) %>% 
  filter(datetime >= min(obsdat$datetime) & datetime <= max(obsdat$datetime))

# combine ph and tidal data, create variables needed for GAM
alldat <- obsdat %>% 
  full_join(tiddat, by = 'datetime') %>% 
  rename(DateTimeStamp = datetime) %>% 
  group_by(loc) %>% 
  mutate(
    date = as.Date(DateTimeStamp, tz = attr(DateTimeStamp, 'tzone')),
    sec = second(DateTimeStamp),
    min = minute(DateTimeStamp),
    hr = hour(DateTimeStamp), 
    mindate = date - min(date),
    secs = hr * 3600 + min * 60 + sec,
    dec_hr = secs / (60 * 60),
    dec_day = as.numeric(mindate) + (secs / 86400)
  ) %>% 
  select(DateTimeStamp, date, loc, pH, Tide, dec_hr, dec_day)

dtdres <- alldat %>% 
  group_by(loc) %>% 
  nest() %>% 
  mutate(
    dtd = purrr::map(data, function(x){
      
      # mod <- gam(pH ~ te(dec_day, dec_hr, Tide, bs = c("tp", "cc", "tp")), data = x,
                   # knots = list(doy = c(0, 24)))
      
      # mod <- gam(pH ~ s(dec_day, k = 70) + ti(dec_hr, Tide, bs = c("cc", "tp")), data = x,
                   # knots = list(doy = c(0, 24), Tide = 40))
      
      mod <- gam(pH ~ dec_day + s(dec_day, k = 50) + 
             s(dec_hr, bs = 'cc') + 
             ti(dec_day, dec_hr ,bs = c('tp', 'cc')) + 
             s(Tide, k = 40) + 
             ti(Tide, dec_hr, bs= c('tp', 'cc')) + 
             ti(Tide, dec_day, bs = c('tp', 'tp')) +
             ti(Tide, dec_hr, dec_day, bs = c('tp', 'cc', 'tp')),
           knots= list(dec_hr = c(0, 23)), select = T,
           data = x)

      # get flow-normalized data
      prdnrm <- range(x$Tide) %>% 
        {seq(.[1], .[2], length.out = 10)} %>% 
        crossing(
          Tide = ., 
          x[, c('dec_hr', 'dec_day')]
        ) %>% 
        mutate(
          prd = predict(mod, .)
        ) %>% 
        group_by(dec_day, dec_hr) %>% 
        summarise(
          pH_dtd = mean(prd, na.rm = T), 
          .groups = 'drop'
        )
      
      out <- x %>% 
        full_join(prdnrm, by = c('dec_day', 'dec_hr')) %>% 
        select(
          DateTimeStamp, 
          date,
          pH,
          pH_dtd
        ) %>% 
        gather('var', 'val',  -DateTimeStamp, -date) 
      
      return(out)
      
    })
  ) %>% 
  select(loc, dtd) %>% 
  unnest('dtd')
```

Plots of observed pH (red) and detided pH (blue), by location. 

```{r, fig.height = 7, fig.width = 9}
ggplot(dtdres, aes(x = DateTimeStamp, y = val, color = var)) +
  geom_line() +
  facet_wrap(~loc, ncol = 1, scales = 'free_y') +
  theme_minimal() + 
  labs(
    y = 'pH', 
    x = NULL, 
    color = NULL
  )
```

Plots of diel pH range for observed pH (top) and detided pH (bottom), by location.

```{r, fig.height = 4, fig.width = 9}
dtdsum <- dtdres %>% 
  group_by(loc, date, var) %>% 
  summarise(
    rng = diff(range(val, na.rm = T)), 
    ave = mean(val, na.rm = T),
    .groups = 'drop'
  )

ggplot(dtdsum, aes(x = date, y = rng, color = loc)) +
  geom_line(size = 1) + 
  facet_wrap(~var, ncol = 1, scales = 'free_y') +
  theme_minimal() + 
  labs(
    x = NULL, 
    y = 'daily pH range', 
    color = NULL
  )

ggplot(dtdsum, aes(x = date, y = ave, color = loc)) +
  geom_line(size = 1) + 
  facet_wrap(~var, ncol = 1, scales = 'free_y') +
  theme_minimal() + 
  labs(
    x = NULL, 
    y = 'daily pH average', 
    color = NULL
  )

```
