---
output: 
  html_document:
    code_folding: hide
css: styles.css
---
  
# Evaluation of oyster dissolution {.tabset}
  
```{r setup, message = F, warning = F, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(patchwork)
library(ggbeeswarm)
library(psycho)
library(lmerTest)
library(hrbrthemes)
library(kableExtra)
library(shiny)
library(janitor)
library(patchwork)
library(modelbased)

source('R/funcs.R')

dissdat <- read.csv('data/raw/SEM scoring datasheet_MRVERSION.csv') %>% 
  clean_names() %>% 
  filter(week != 0) %>% 
  select(
    jar, 
    id = individual_id, 
    species, 
    week, 
    trt = treatment,
    rep, 
    scr = dissolution_score1
  ) %>% 
  group_by(jar, id, species, week, trt) %>% 
  summarise(
    val = mean(scr, na.rm = T),
    .groups = 'drop'
    ) %>% 
  mutate(
    val = val / 3,
    jar = factor(jar),
    trt = factor(trt, levels = c("7.7C", "7.7A0.2", "7.7A0.5", "8.0C", "8.0A0.2"))
  )

# treatment colors
cls <- RColorBrewer::brewer.pal(6, 'BrBG')
cls <- c(cls[1:3], cls[c(6, 4)])
names(cls) <- levels(dissdat$trt)

# all comparisons
dissmodsall <- dissdat %>%
  group_by(species) %>% 
  nest %>% 
  mutate(
    mixmod = purrr::map(data, function(x){

      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
      
      out <- lmerTest::lmer(val ~ trt * week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    mixmodnoint = purrr::map(data, function(x){
      
      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
    
      out <- lmerTest::lmer(val ~ trt + week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    anomod = purrr::map(mixmod, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    anomodnoint = purrr::map(mixmodnoint, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    plomod = purrr::pmap(list(species, mixmod), function(species, mixmod){

      # estimates
      mnsval <- estimate_means(mixmod)
      
      # sample size
      n <- mixmod@frame %>% nrow
      
      # labels
      subttl <- paste0('Standardized dissolution, ', species, ' oyster')
      captns <- paste0('Significance is where CI does not include zero, alpha = 0.05, total n = ', n)
      
      # mean esimate plots
      p1 <- ggplot(mnsval, aes(x = week, y = Mean, group = trt, colour = trt, fill = trt)) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high, colour = trt), width = 0, position = position_dodge(0.3), size = 1) + 
        geom_line(position = position_dodge(0.3)) + 
        geom_point(size = 3, position = position_dodge(0.3), pch = 21, colour = 'black') + 
        labs(x = 'Exposure week', y = 'Estimated means (+/- 95% CI)', title = 'Treatment estimates', subtitle = subttl, caption = captns) + 
        scale_colour_manual(values = cls) + 
        scale_fill_manual(values = cls) + 
        theme_ipsum() + 
        theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          legend.title = element_blank()
        )
      
      p1
      
    })
  )

# 77C vs 8.0C
dissmods7780 <- dissdat %>%
  filter(trt %in% c("7.7C", "8.0C")) %>% 
  mutate(trt = fct_drop(trt)) %>% 
  group_by(species) %>% 
  nest %>% 
  mutate(
    mixmod = purrr::map(data, function(x){

      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
      
      out <- lmerTest::lmer(val ~ trt * week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    mixmodnoint = purrr::map(data, function(x){
      
      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
    
      out <- lmerTest::lmer(val ~ trt + week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    anomod = purrr::map(mixmod, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    anomodnoint = purrr::map(mixmodnoint, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    plomod = purrr::pmap(list(species, mixmod), function(species, mixmod){

      # estimates
      mnsval <- estimate_means(mixmod)
      
      # sample size
      n <- mixmod@frame %>% nrow
      
      # labels
      subttl <- paste0('Standardized dissolution, ', species, ' oyster')
      captns <- paste0('Significance is where CI does not include zero, alpha = 0.05, total n = ', n)
      
      # mean esimate plots
      p1 <- ggplot(mnsval, aes(x = week, y = Mean, group = trt, colour = trt, fill = trt)) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high, colour = trt), width = 0, position = position_dodge(0.3), size = 1) + 
        geom_line(position = position_dodge(0.3)) + 
        geom_point(size = 3, position = position_dodge(0.3), pch = 21, colour = 'black') + 
        labs(x = 'Exposure week', y = 'Estimated means (+/- 95% CI)', title = 'Treatment estimates', subtitle = subttl, caption = captns) + 
        scale_colour_manual(values = cls) + 
        scale_fill_manual(values = cls) + 
        theme_ipsum() + 
        theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          legend.title = element_blank()
        )
      
      p1
      
    })
  )

# 7.7
dissmods77 <- dissdat %>%
  filter(trt %in% c("7.7C", "7.7A0.2", "7.7A0.5")) %>% 
  mutate(trt = fct_drop(trt)) %>% 
  group_by(species) %>% 
  nest %>% 
  mutate(
    mixmod = purrr::map(data, function(x){

      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
      
      out <- lmerTest::lmer(val ~ trt * week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    mixmodnoint = purrr::map(data, function(x){
      
      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
    
      out <- lmerTest::lmer(val ~ trt + week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    anomod = purrr::map(mixmod, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    anomodnoint = purrr::map(mixmodnoint, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    plomod = purrr::pmap(list(species, mixmod), function(species, mixmod){

      # estimates
      mnsval <- estimate_means(mixmod)
      
      # sample size
      n <- mixmod@frame %>% nrow
      
      # labels
      subttl <- paste0('Standardized dissolution, ', species, ' oyster')
      captns <- paste0('Significance is where CI does not include zero, alpha = 0.05, total n = ', n)
      
      # mean esimate plots
      p1 <- ggplot(mnsval, aes(x = week, y = Mean, group = trt, colour = trt, fill = trt)) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high, colour = trt), width = 0, position = position_dodge(0.3), size = 1) + 
        geom_line(position = position_dodge(0.3)) + 
        geom_point(size = 3, position = position_dodge(0.3), pch = 21, colour = 'black') + 
        labs(x = 'Exposure week', y = 'Estimated means (+/- 95% CI)', title = 'Treatment estimates', subtitle = subttl, caption = captns) + 
        scale_colour_manual(values = cls) + 
        scale_fill_manual(values = cls) + 
        theme_ipsum() + 
        theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          legend.title = element_blank()
        )
      
      p1
      
    })
  )

# 8.0
dissmods80 <- dissdat %>%
  filter(trt %in% c("8.0C", "8.0A0.2")) %>% 
  mutate(trt = fct_drop(trt)) %>% 
  group_by(species) %>% 
  nest %>% 
  mutate(
    mixmod = purrr::map(data, function(x){

      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
      
      out <- lmerTest::lmer(val ~ trt * week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    mixmodnoint = purrr::map(data, function(x){
      
      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
    
      out <- lmerTest::lmer(val ~ trt + week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    anomod = purrr::map(mixmod, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    anomodnoint = purrr::map(mixmodnoint, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    plomod = purrr::pmap(list(species, mixmod), function(species, mixmod){

      # estimates
      mnsval <- estimate_means(mixmod)
      
      # sample size
      n <- mixmod@frame %>% nrow
      
      # labels
      subttl <- paste0('Standardized dissolution, ', species, ' oyster')
      captns <- paste0('Significance is where CI does not include zero, alpha = 0.05, total n = ', n)
      
      # mean esimate plots
      p1 <- ggplot(mnsval, aes(x = week, y = Mean, group = trt, colour = trt, fill = trt)) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high, colour = trt), width = 0, position = position_dodge(0.3), size = 1) + 
        geom_line(position = position_dodge(0.3)) + 
        geom_point(size = 3, position = position_dodge(0.3), pch = 21, colour = 'black') + 
        labs(x = 'Exposure week', y = 'Estimated means (+/- 95% CI)', title = 'Treatment estimates', subtitle = subttl, caption = captns) + 
        scale_colour_manual(values = cls) + 
        scale_fill_manual(values = cls) + 
        theme_ipsum() + 
        theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          legend.title = element_blank()
        )
      
      p1
      
    })
  )

# 7.7A0.2, 7.7A0.5, 8.0A0.2
dissmods7780a <- dissdat %>%
  filter(trt %in% c('7.7A0.2', '7.7A0.5', '8.0A0.2')) %>% 
  mutate(trt = fct_drop(trt)) %>% 
  group_by(species) %>% 
  nest %>% 
  mutate(
    mixmod = purrr::map(data, function(x){

      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
      
      out <- lmerTest::lmer(val ~ trt * week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    mixmodnoint = purrr::map(data, function(x){
      
      tomod <- x %>% 
        mutate(
          week = factor(week), 
          jar = fct_drop(jar), 
          trt = fct_drop(trt)
        )
    
      out <- lmerTest::lmer(val ~ trt + week + (1|jar), data = tomod)
      
      return(out)
      
    }),
    anomod = purrr::map(mixmod, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    anomodnoint = purrr::map(mixmodnoint, function(x){
      
      out <- anova(x)
      
      return(out)
      
    }), 
    plomod = purrr::pmap(list(species, mixmod), function(species, mixmod){

      # estimates
      mnsval <- estimate_means(mixmod)
      
      # sample size
      n <- mixmod@frame %>% nrow
      
      # labels
      subttl <- paste0('Standardized dissolution, ', species, ' oyster')
      captns <- paste0('Significance is where CI does not include zero, alpha = 0.05, total n = ', n)
      
      # mean esimate plots
      p1 <- ggplot(mnsval, aes(x = week, y = Mean, group = trt, colour = trt, fill = trt)) + 
        geom_errorbar(aes(ymin = CI_low, ymax = CI_high, colour = trt), width = 0, position = position_dodge(0.3), size = 1) + 
        geom_line(position = position_dodge(0.3)) + 
        geom_point(size = 3, position = position_dodge(0.3), pch = 21, colour = 'black') + 
        labs(x = 'Exposure week', y = 'Estimated means (+/- 95% CI)', title = 'Treatment estimates', subtitle = subttl, caption = captns) + 
        scale_colour_manual(values = cls) + 
        scale_fill_manual(values = cls) + 
        theme_ipsum() + 
        theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          legend.title = element_blank()
        )
      
      p1
      
    })
  )
```

## All treatments {.tabset .tabset-pills}

### Olympia oyster

```{r}
dat <- dissmodsall %>% 
  filter(species == 'Olympia')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

### Pacific oyster

```{r}
dat <- dissmodsall %>% 
  filter(species == 'Pacific')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

## 7.7C, 8.0C {.tabset .tabset-pills}

### Olympia oyster

```{r}
dat <- dissmods7780 %>% 
  filter(species == 'Olympia')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

### Pacific oyster

```{r}
dat <- dissmods7780 %>% 
  filter(species == 'Pacific')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

## 7.7C, 7.7A0.2, 7.7A0.5 {.tabset .tabset-pills}

### Olympia oyster

```{r}
dat <- dissmods77 %>% 
  filter(species == 'Olympia')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

### Pacific oyster

```{r}
dat <- dissmods77 %>% 
  filter(species == 'Pacific')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

## 8.0C, 8.0A0.2 {.tabset .tabset-pills}

### Olympia oyster

```{r}
dat <- dissmods80 %>% 
  filter(species == 'Olympia')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

### Pacific oyster

```{r}
dat <- dissmods80 %>% 
  filter(species == 'Pacific')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

## 7.7A0.2, 7.7A0.5, 8.0A0.2 {.tabset .tabset-pills}

### Olympia oyster

```{r}
dat <- dissmods7780a %>% 
  filter(species == 'Olympia')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```

### Pacific oyster

```{r}
dat <- dissmods7780a %>% 
  filter(species == 'Pacific')

dat %>% 
  pull(anomodnoint) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week + treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML

dat %>% 
  pull(anomod) %>% 
  .[[1]] %>% 
  knitr::kable(format = 'html', digits = 2, caption = 'Dissolution vs week x treatment') %>%
  kable_styling(full_width = T, font_size = 14) %>% 
  HTML
```

```{r, fig.height = 5, fig.width = 6, out.width = '70%', results = 'hide', fig.align = 'center'}
dat %>% 
  pull(plomod)
```