---
output: 
  html_document:
    code_folding: hide
css: styles.css
---
  
# Oyster exposure experiments, length and weight analyses {.tabset}

```{r setup, message = F, warning = F, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(janitor)
library(readxl)
library(patchwork)
source("R/funcs.R")

# consistent treatment terminology names
trts <- tibble(
  shrtlab = c("7.7C", "7.7A0.2", "7.7A0.5", "8.0C", "8.0A0.2"),
  lngslab = c( "7.7 Constant", "7.7 Fluctuating 0.2A", "7.7 Fluctuating 0.5A", "8.0 Constant", "8.0 Fluctuating 0.2A")
)

# consistent response variable names for weight
rsps <- tibble(
  shrtlab = c("final_length", "final_width", "shell_weight", "tissue_weight"),
  lngslab = c("Final length (cm)", "Final width (cm)", "Shell weight (g)", "Tissue weight (g)")
)

# length data
# initial column measured a few days prior to week zero
alllen <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    final_length = case_when(
      week == 0 & is.na(final_length) ~ initial_length, 
      T ~ final_length
    ),
    final_width = case_when(
      week == 0 & is.na(final_width) ~ initial_width,
      T ~ final_width
    )
  ) %>% 
  gather('var', 'val', -week, -trt, -jar, -id, -species) %>% 
  filter(!var %in% c('initial_length', 'initial_width'))

# weight data
allwts <- read.csv(here::here('data/raw/Weight_with dead but not multiple_Kelp_4_3.csv'), stringsAsFactors = F) %>% 
  clean_names() %>% 
  # filter(week != 0) %>% 
  filter(species != '') %>% 
  mutate(species = gsub('\\s*$', '', species)) %>% 
  rename(
    id = individual_id, 
    jar = i_jar,
    trt = treatment
  ) %>%
  select(week, trt, jar, id, species, shell_weight, tissue_weight) %>% 
  gather('var', 'val', shell_weight, tissue_weight) %>% 
  na.omit 

alldat <- bind_rows(allwts, alllen) %>% 
  mutate(
    trt = factor(trt, levels = trts$shrtlab, labels = trts$shrtlab), 
    var = factor(var, levels = rsps$shrtlab, labels = rsps$lngslab)
  )

# week combinations
wks <- sort(unique(alldat$week)) %>% 
  combn(2) %>% 
  t %>% 
  data.frame %>% 
  rename(
    week1 = X1, 
    week2 = X2
  )

grds <- alldat %>% 
  select(trt, species, var) %>% 
  unique() %>% 
  crossing(wks) %>% 
  mutate(
    res = purrr::pmap(list(trt, species, var, week1, week2), function(trt, species, var, week1, week2){

      specsel <- species
      varsel <- var
      trtsel <- trt
      
      tomod <- alldat %>%
        filter(species %in% specsel) %>%
        filter(var %in% varsel) %>%
        filter(trt %in% trtsel)

      val1 <- tomod %>%
        filter(week == week1) %>%
        pull(val)

      val2 <- tomod %>%
        filter(week == week2) %>%
        pull(val)

      est <- t.test(val1, val2)

      perc <-  as.numeric(100 * diff(est$estimate) / est$estimate[2])
      pout <- p_ast(est$p.value)
      out <- data.frame(perc, pout)

      return(out)

    })
  ) %>% 
  unnest('res')
```

## Length

```{r, fig.height = 14, fig.width = 14}

lenvars <- c('Final length (cm)', 'Final width (cm)')
toplo1 <- alldat %>% 
  filter(var %in% lenvars) %>% 
  group_by(week, trt, species, var) %>% 
  summarise(
    aveval = mean(val, na.rm = T), 
    lowval = t.test(val)$conf.int[1],
    uppval = t.test(val)$conf.int[2]
  )

p1 <- ggplot(toplo1, aes(x = week, y = aveval)) + 
  geom_point(size = 2) + 
  geom_errorbar(aes(ymax = uppval, ymin = lowval), width = 1) + 
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Average values and 95% confidence intervals across time periods', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average (+/- 95% CI)', 
    x = 'Week'
  )

toplo2 <- grds %>% 
  filter(var %in% lenvars)

p2 <- ggplot(toplo2, aes(x = week1, y = week2, fill = perc)) + 
  geom_tile(color = 'black') + 
  geom_text(aes(label = pout)) + 
  scale_x_continuous('Week', expand = c(0, 0), breaks = c(0, 2, 4)) +
  scale_y_continuous('Week', expand = c(0, 0), breaks = c(2, 4, 6)) +
  scale_fill_gradient2(low = 'lightgreen', mid = 'white', high = 'lightblue') +
  # scale_fill_distiller('% diff.', palette = 'Purples', direction = 1) +
  facet_grid(trt ~ species + var) +
  theme(
    panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank()
  ) + 
  labs(
    title = 'Differences in means between experiment time points', 
    subtitle = 'Significant differences are indicated by text'
  )

toplo3 <- alldat %>% 
  filter(var %in% lenvars)

p3 <- ggplot(toplo3, aes(x = val)) + 
  stat_ecdf(aes(colour = trt), size = 1) +
  facet_grid(week ~ species + var, scales = 'free') +
  scale_colour_viridis_d() +
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Cumulative distribution plots', 
    subtitle = 'Panels separated by species, week, and response measure',
    y = 'Cumulative frequency', 
    x = 'Size (cm)'
  )

p1 + p2 + p3 + plot_layout(ncol = 2)
```

## Length across individuals

```{r, fig.height = 35, fig.width = 12}
# length data
# initial column measured a few days prior to week zero
toplo1 <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, 
         initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  gather('var', 'val', final_length, initial_length, final_width, initial_width) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'initial' ~ 0, 
      T ~ week
    )
  ) %>% 
  unite('jar_id', jar, id)

p1 <- ggplot(toplo1, aes(x = week, y = val, gruop = jar_id)) + 
  geom_line() + 
  geom_point(size = 2) + 
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking growth by individuals from time zero', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Size (cm)', 
    x = 'Week'
  )
  
toplo2 <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, 
           initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    delt_length = final_length - initial_length, 
    init_length = 0,
    delt_width = final_width - initial_width, 
    init_width = 0
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, delt_length, init_length, delt_width, init_width) %>% 
  gather('var', 'val', delt_length, init_length, delt_width, init_width) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0, 
      T ~ week
    )
  ) %>% 
  unite('jar_id', jar, id)

p2 <- ggplot(toplo2, aes(x = week, y = val, gruop = jar_id)) + 
  geom_line() + 
  geom_point(size = 2) + 
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking growth by individuals from time zero', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Size change from time zero (cm)', 
    x = 'Week'
  ) + 
  geom_hline(yintercept = 0, linetype = 'dotted', colour = 'black')

toplo3 <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, 
         initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    scld_length = (final_length - initial_length) / week + initial_length,
    init_length = initial_length,
    scld_width = (final_width - initial_width) / week + initial_width,
    init_width = initial_width
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, scld_length, init_length, scld_width, init_width) %>% 
  gather('var', 'val', scld_length, init_length, scld_width, init_width) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0, 
      T ~ 1
    )
  ) %>% 
  unite('jar_id', jar, id)

p3 <- ggplot(toplo3, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, all weeks', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled growth (cm/week)', 
    x = 'Week'
  ) 

toplo4 <- toplo3 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p4 <- ggplot(toplo4, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, all weeks',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average Scaled growth (cm/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo5 <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, 
         initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    scld_length = (final_length - initial_length) / week + initial_length,
    init_length = initial_length,
    scld_width = (final_width - initial_width) / week + initial_width,
    init_width = initial_width
  ) %>% 
  filter(week == 2) %>% 
  select(week, trt, jar, id, species, scld_length, init_length, scld_width, init_width) %>% 
  gather('var', 'val', scld_length, init_length, scld_width, init_width) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0, 
      T ~ 1
    )
  ) %>% 
  unite('jar_id', jar, id)

p5 <- ggplot(toplo5, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, week two only', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled growth (cm/week)', 
    x = 'Week'
  ) 

toplo6 <- toplo5 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p6 <- ggplot(toplo6, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, week two only',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average Scaled growth (cm/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo7 <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, 
         initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    scld_length = (final_length - initial_length) / week + initial_length,
    init_length = initial_length,
    scld_width = (final_width - initial_width) / week + initial_width,
    init_width = initial_width
  ) %>% 
  filter(week == 4) %>% 
  select(week, trt, jar, id, species, scld_length, init_length, scld_width, init_width) %>% 
  gather('var', 'val', scld_length, init_length, scld_width, init_width) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0, 
      T ~ 1
    )
  ) %>% 
  unite('jar_id', jar, id)

p7 <- ggplot(toplo7, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, week four only', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled growth (cm/week)', 
    x = 'Week'
  ) 

toplo8 <- toplo7 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p8 <- ggplot(toplo8, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, week four only',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average Scaled growth (cm/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo9 <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, 
         initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    scld_length = (final_length - initial_length) / week + initial_length,
    init_length = initial_length,
    scld_width = (final_width - initial_width) / week + initial_width,
    init_width = initial_width
  ) %>% 
  filter(week == 6) %>% 
  select(week, trt, jar, id, species, scld_length, init_length, scld_width, init_width) %>% 
  gather('var', 'val', scld_length, init_length, scld_width, init_width) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0, 
      T ~ 1
    )
  ) %>% 
  unite('jar_id', jar, id)

p9 <- ggplot(toplo9, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, week six only', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled growth (cm/week)', 
    x = 'Week'
  ) 

toplo10 <- toplo9 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p10 <- ggplot(toplo4, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled growth by individuals from time zero, week six only',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average Scaled growth (cm/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo11 <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, 
         initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    delt_length = final_length - initial_length, 
    init_length = 0,
    delt_width = final_width - initial_width, 
    init_width = 0
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, delt_length, init_length, delt_width, init_width) %>% 
  gather('var', 'val', delt_length, init_length, delt_width, init_width) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0, 
      T ~ week
    )
  ) %>% 
  unite('jar_id', jar, id) %>% 
  filter(week != 0) %>% 
  mutate(
    val = case_when(
      sign(val) %in% c(0, 1) ~ 1, 
      sign(val) == -1 ~ -1
    )
  ) %>% 
  group_by(week, trt, species, period, var, val) %>% 
  summarise(cnt = sum(val)) %>% 
  na.omit() %>% 
  ungroup %>% 
  mutate(val = factor(val, levels = c(1, -1), labels = c('positive', 'negative')))
  
p11 <- ggplot(toplo11, aes(x = week, y = cnt, fill = factor(val))) + 
  geom_bar(stat = 'identity') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Tracking growth by individuals from time zero', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Count of individuals with positive or negative growth', 
    x = 'Week'
  ) 

p1 + p2 + p11 + plot_spacer() + p3 + p4 + p5 + p6 + p7 + p8 + p9 + p10 + plot_layout(ncol = 2)
```

## Weight 

```{r, fig.height = 14, fig.width = 14}

wgtvars <- c('Shell weight (g)', 'Tissue weight (g)')
toplo1 <- alldat %>% 
  filter(var %in% wgtvars) %>% 
  group_by(week, trt, species, var) %>% 
  summarise(
    aveval = mean(val, na.rm = T), 
    lowval = t.test(val)$conf.int[1],
    uppval = t.test(val)$conf.int[2]
  )

p1 <- ggplot(toplo1, aes(x = week, y = aveval)) + 
  geom_point(size = 2) + 
  geom_errorbar(aes(ymax = uppval, ymin = lowval), width = 1) + 
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Average values and 95% confidence intervals across time periods', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average (+/- 95% CI)', 
    x = 'Week'
  )

toplo2 <- grds %>% 
  filter(var %in% wgtvars)

p2 <- ggplot(toplo2, aes(x = week1, y = week2, fill = perc)) + 
  geom_tile(color = 'black') + 
  geom_text(aes(label = pout)) + 
  scale_x_continuous('Week', expand = c(0, 0), breaks = c(0, 2, 4)) +
  scale_y_continuous('Week', expand = c(0, 0), breaks = c(2, 4, 6)) +
  # scale_fill_distiller('% diff.', palette = 'Purples', direction = 1) + 
  scale_fill_gradient2(low = 'lightgreen', mid = 'white', high = 'lightblue') +
  facet_grid(trt ~ species + var) +
  theme(
    panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank()
  ) + 
  labs(
    title = 'Differences in means between experiment time points', 
    subtitle = 'Significant differences are indicated by text'
  )

toplo3 <- alldat %>% 
  filter(var %in% wgtvars) 

p3 <- ggplot(toplo3, aes(x = val)) + 
  stat_ecdf(aes(colour = trt), size = 1) +
  facet_grid(week ~ species + var, scales = 'free') +
  scale_colour_viridis_d() +
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Cumulative distribution plots', 
    subtitle = 'Panels separated by species, week, and response measure',
    y = 'Cumulative frequency', 
    x = 'Weight (g)'
  )

p1 + p2 + p3 + plot_layout(ncol = 2)
```

## Weight across individuals

```{r, fig.height = 35, fig.width = 12}

# calc initial final from sum of tissue and shell weight
datprp <- read.csv(here::here('data/raw/Weight_with dead but not multiple_Kelp_4_3.csv'), stringsAsFactors = F) %>% 
  clean_names() %>% 
  # filter(week != 0) %>% 
  filter(species != '') %>% 
  mutate(
    species = gsub('\\s*$', '', species),
    whole_organism_weight = case_when(
      is.na(whole_organism_weight) &  !is.na(shell_weight) & !is.na(tissue_weight) ~ shell_weight + tissue_weight, 
      T ~ whole_organism_weight
    )
  ) %>% 
  filter(!is.na(initial_wetweight) & !is.na(whole_organism_weight)) %>% 
  select(week, trt = treatment, jar = i_jar, id = individual_id, species, initial_weight = initial_wetweight, 
         final_weight = whole_organism_weight) 

toplo1 <- datprp %>% 
  gather('var', 'val', initial_weight, final_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  mutate(
    week = case_when(
      period == 'initial' ~ 0L, 
      T ~ week
    )
  ) %>% 
  unite('jar_id', jar, id)

p1 <- ggplot(toplo1, aes(x = week, y = val, group = jar_id)) + 
  geom_line() + 
  geom_point(size = 2) + 
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking weight by individuals from time zero', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Weight (g)', 
    x = 'Week'
  )

toplo2 <- datprp %>% 
  mutate(
    delt_weight = final_weight - initial_weight, 
    init_weight = 0,
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, delt_weight, init_weight) %>% 
  gather('var', 'val', delt_weight, init_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0L, 
      T ~ week
    )
  ) %>% 
  unite('jar_id', jar, id)

p2 <- ggplot(toplo2, aes(x = week, y = val, group = jar_id)) + 
  geom_line() + 
  geom_point(size = 2) + 
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking weight by individuals from time zero', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Weight change from time zero (g)', 
    x = 'Week'
  ) + 
  geom_hline(yintercept = 0, linetype = 'dotted', colour = 'black')

toplo3 <- datprp %>% 
  mutate(
    scld_weight = (final_weight - initial_weight) / week + initial_weight,
    init_weight = initial_weight,
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, scld_weight, init_weight) %>% 
  gather('var', 'val', scld_weight, init_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0L, 
      T ~ 1L
    )
  ) %>% 
  unite('jar_id', jar, id)

p3 <- ggplot(toplo3, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, all weeks', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled weight (g/week)', 
    x = 'Week'
  ) 

toplo4 <- toplo3 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p4 <- ggplot(toplo4, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, all weeks',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average scaled weight (g/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo5 <- datprp %>% 
  mutate(
    scld_weight = (final_weight - initial_weight) / week + initial_weight,
    init_weight = initial_weight,
  ) %>% 
  filter(week == 2) %>% 
  select(week, trt, jar, id, species, scld_weight, init_weight) %>% 
  gather('var', 'val', scld_weight, init_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0L, 
      T ~ 1L
    )
  ) %>% 
  unite('jar_id', jar, id)

p5 <- ggplot(toplo5, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, week two only', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled weight (g/week)', 
    x = 'Week'
  ) 

toplo6 <- toplo5 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p6 <- ggplot(toplo6, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, week two only',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average Scaled weight (g/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo7 <- datprp %>% 
  mutate(
    scld_weight = (final_weight - initial_weight) / week + initial_weight,
    init_weight = initial_weight,
  ) %>% 
  filter(week == 4) %>% 
  select(week, trt, jar, id, species, scld_weight, init_weight) %>% 
  gather('var', 'val', scld_weight, init_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0L, 
      T ~ 1L
    )
  ) %>% 
  unite('jar_id', jar, id)

p7 <- ggplot(toplo7, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, week four only', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled weight (g/week)', 
    x = 'Week'
  ) 

toplo8 <- toplo7 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p8 <- ggplot(toplo8, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, week four only',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average Scaled weight (g/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo9 <- datprp %>% 
  mutate(
    scld_weight = (final_weight - initial_weight) / week + initial_weight,
    init_weight = initial_weight,
  ) %>% 
  filter(week == 6) %>% 
  select(week, trt, jar, id, species, scld_weight, init_weight) %>% 
  gather('var', 'val', scld_weight, init_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0L, 
      T ~ 1L
    )
  ) %>% 
  unite('jar_id', jar, id)

p9 <- ggplot(toplo9, aes(x = week, y = val, group = jar_id)) + 
  geom_line(size = 0.5) +
  geom_point(size = 2) + 
  # geom_point(aes(y = aveval), colour = 'black', size = 3) +
  # geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  # geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, week six only', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Scaled weight (g/week)', 
    x = 'Week'
  ) 

toplo10 <- toplo9 %>% 
  group_by(week, trt, species, period, var) %>% 
  summarize(
    aveval = mean(val, na.rm = T), 
    uprval = t.test(val)$conf.int[2],
    lwrval = t.test(val)$conf.int[1]
  )

p10 <- ggplot(toplo4, aes(x = week)) + 
  geom_point(aes(y = aveval), colour = 'black', size = 3) +
  geom_errorbar(aes(ymin = lwrval, ymax = uprval), colour = 'black', width = 0.1) +
  geom_line(aes(y = aveval), colour = 'black') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(0, 1)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank()
  ) + 
  labs(
    title = 'Tracking scaled weight by individuals from time zero, week six only',  
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Average Scaled weight (g/week) +/- 95% CI', 
    x = 'Week'
  ) 

toplo11 <- datprp %>% 
  mutate(
    delt_weight = final_weight - initial_weight, 
    init_weight = 0,
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, delt_weight, init_weight) %>% 
  gather('var', 'val', delt_weight, init_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0L, 
      T ~ week
    )
  ) %>% 
  unite('jar_id', jar, id) %>% 
  filter(week != 0) %>% 
  mutate(
    val = case_when(
      sign(val) %in% c(0, 1) ~ 1, 
      sign(val) == -1 ~ -1
    )
  ) %>% 
  group_by(week, trt, species, period, var, val) %>% 
  summarise(cnt = sum(val)) %>% 
  na.omit() %>% 
  ungroup %>% 
  mutate(val = factor(val, levels = c(1, -1), labels = c('positive', 'negative')))

p11 <- ggplot(toplo11, aes(x = week, y = cnt, fill = factor(val))) + 
  geom_bar(stat = 'identity') +
  facet_grid(trt ~ species + var) +
  scale_x_continuous(breaks = c(2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Tracking weight by individuals from time zero', 
    subtitle = 'Panels separated by species, treatment, and response measure',
    y = 'Count of individuals with positive or negative weight change', 
    x = 'Week'
  )

p1 + p2 + p11 + plot_spacer() + p3 + p4 + p5 + p6 + p7 + p8 + p9 + p10 + plot_layout(ncol = 2)
```

## Lenght vs weight

```{r, fig.height = 14, fig.width = 14}
lendat <- alllen %>%
  group_by_at(vars(-val)) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  spread(var, val)

wtsdat <- allwts %>%
  group_by_at(vars(-val)) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  spread(var, val)

toplo1 <- inner_join(lendat, wtsdat, by = c('week', 'trt', 'jar', 'id', 'species')) %>% 
  mutate(
    trt = factor(trt, levels = trts$shrtlab, labels = trts$shrtlab)
  )

p1 <- ggplot(toplo1, aes(x = final_length, y = shell_weight, colour = trt)) + 
  geom_point(alpha = 0.7) + 
  # geom_smooth(se = F, method = 'lm') + 
  scale_colour_viridis_d() +
  facet_grid(week ~ species) +
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Tracking shell weight vs length', 
    subtitle = 'Panels separated by species, week, and treatment',
    y = 'Shell weight (g)', 
    x = 'Final length (cm)'
  )

p2 <- ggplot(toplo1, aes(x = final_length, y = final_width, colour = trt)) + 
  geom_point(alpha = 0.7) + 
  # geom_smooth(se = F, method = 'lm') + 
  scale_colour_viridis_d() +
  facet_grid(week ~ species) +
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Tracking width vs length', 
    subtitle = 'Panels separated by species, week, and treatment',
    y = 'Final width (cm)', 
    x = 'Final length (cm)'
  )

p3 <- ggplot(toplo1, aes(x = final_length, y = tissue_weight, colour = trt)) + 
  geom_point(alpha = 0.7) + 
  # geom_smooth(se = F, method = 'lm') + 
  scale_colour_viridis_d() +
  facet_grid(week ~ species) +
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Tracking tissue weight vs length', 
    subtitle = 'Panels separated by species, week, and treatment',
    y = 'Tissue weight (g)', 
    x = 'Final length (cm)'
  )

p4 <- ggplot(toplo1, aes(x = tissue_weight, y = shell_weight, colour = trt)) + 
  geom_point(alpha = 0.7) + 
  # geom_smooth(se = F, method = 'lm') + 
  scale_colour_viridis_d() +
  facet_grid(week ~ species) +
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Tracking shell weight vs tissue weight', 
    subtitle = 'Panels separated by species, week, and treatment',
    y = 'Shell weight (g)', 
    x = 'Tissue weight (g)'
  )

p1 + p2 + p3 + p4 + plot_layout(ncol = 2)
```

## Survival 

```{r, fig.height = 7, fig.width = 7}
toplo1 <- read.csv(here::here('data/raw/Weight_with dead but not multiple_Kelp_4_3.csv'), stringsAsFactors = F) %>% 
  clean_names() %>% 
  # filter(week != 0) %>% 
  filter(species != '') %>% 
  mutate(species = gsub('\\s*$', '', species)) %>% 
  rename(
    id = individual_id, 
    jar = i_jar,
    trt = treatment
  ) %>% 
  select(week, trt, jar, id, species, dead) %>% 
  mutate(
    dead = case_when(
      dead %in% c('x', 'X') ~ 1, 
      T ~ 0
    )
  ) %>% 
  group_by(week, trt, species) %>% 
  summarise(percdead = 100 * sum(dead) / length(dead)) %>%
  ungroup() %>% 
  filter(trt != '') %>% 
  mutate(
    trt = factor(trt, levels = trts$shrtlab, labels = trts$shrtlab)
  )

p1 <- ggplot(toplo1, aes(x = week, y = percdead, fill = trt)) + 
  geom_bar(stat = 'identity') + 
  scale_fill_viridis_d() + 
  facet_grid(trt ~ species) +
  scale_x_continuous(breaks = c(0, 2, 4, 6)) + 
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.title = element_blank()
  ) + 
  labs(
    title = 'Percent dead by week', 
    subtitle = 'Panels separated by species, treatment',
    y = '% dead at each time point', 
    x = 'Week'
  )

toplo2 <- read.csv(here::here('data/raw/Weight_with dead but not multiple_Kelp_4_3.csv'), stringsAsFactors = F) %>% 
  clean_names() %>% 
  # filter(week != 0) %>% 
  filter(species != '') %>% 
  mutate(species = gsub('\\s*$', '', species)) %>% 
  rename(
    id = individual_id, 
    jar = i_jar,
    trt = treatment
  ) %>% 
  select(week, trt, jar, id, species, dead) %>% 
  mutate(
    dead = case_when(
      dead %in% c('x', 'X') ~ 1, 
      T ~ 0
    )
  ) %>% 
  group_by(trt, species) %>% 
  summarise(percdead = 100 * sum(dead) / length(dead)) %>%
  ungroup() %>% 
  filter(trt != '') %>% 
  mutate(
    trt = factor(trt, levels = trts$shrtlab, labels = trts$shrtlab)
  )

p2 <- ggplot(toplo2, aes(x = trt, y = percdead, fill = trt)) + 
  geom_bar(stat = 'identity') + 
  scale_fill_viridis_d() + 
  facet_grid( ~ species) +
  theme_bw() + 
  theme(
    # panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = 'none'
  ) + 
  labs(
    title = 'Percent dead across weeks', 
    subtitle = 'Panels separated by species',
    y = '% dead', 
    x = 'Treatment'
  )

p1 + p2 + plot_layout(ncol = 1, height = c(1, 0.25), guides = 'collect')
```

