---
output: 
  html_document:
    code_folding: hide
css: styles.css
---
  
# Evaluation of oyster exposure experiments, length analyses part 2{.tabset}
  
```{r setup, message = F, warning = F, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(janitor)
library(readxl)

source("R/funcs.R")

# consistent treatment terminology names
trts <- tibble(
  shrtlab = c("7.7C", "7.7A0.2", "7.7A0.5", "8.0C", "8.0A0.2"),
  lngslab = c( "7.7 Constant", "7.7 Fluctuating 0.2A", "7.7 Fluctuating 0.5A", "8.0 Constant", "8.0 Fluctuating 0.2A")
)

# consistent response variable terminology names
rspslen <- tibble(
  shrtlab = c("final_length", "final_width"),
  lngslab = c("Final length (cm)", "Final width (cm)")
)

# initial column measured a few days prior to week zero
alllen <- read_excel(here::here('data/raw/Length_kelp_4_3_2020.xlsx')) %>% 
  clean_names() %>% 
  select(week, trt = treatment, jar, id = individual_id, species, final_length = length_cm_final, initial_length = length_cm_initial, final_width = width_cm_final, initial_width = width_cm_initial) %>% 
  mutate(
    final_length = case_when(
      week == 0 & is.na(final_length) ~ initial_length, 
      T ~ final_length
    ),
    final_width = case_when(
      week == 0 & is.na(final_width) ~ initial_width,
      T ~ final_width
    )
  ) %>% 
  gather('var', 'val', -week, -trt, -jar, -id, -species) %>% 
  filter(!var %in% c('initial_length', 'initial_width')) %>% 
  mutate(
    var = factor(var, levels = rspslen$shrtlab, labels = rspslen$lngslab), 
    trt = factor(trt, levels = trts$shrtlab, labels = trts$shrtlab), 
    jar = factor(jar)
  ) %>% 
  arrange(species, var, week)

wks <- unique(alllen$week) %>% 
  combn(2) %>% 
  t %>% 
  data.frame %>% 
  rename(
    week1 = X1, 
    week2 = X2
  )

grds <- alllen %>% 
  select(trt, species, var) %>% 
  unique() %>% 
  crossing(wks) %>% 
  mutate(
    res = purrr::pmap(list(trt, species, var, week1, week2), function(trt, species, var, week1, week2){

      tomod <- alllen %>%
        dplyr::filter(species %in% species) %>%
        filter(var %in% var) %>%
        filter(trt %in% trt)

      val1 <- tomod %>%
        filter(week == week1) %>%
        pull(val)

      val2 <- tomod %>%
        filter(week == week2) %>%
        pull(val)

      est <- t.test(val1, val2)

      perc <-  as.numeric(100 * diff(est$estimate) / est$estimate[2])
      pout <- p_ast(est$p.value)
      out <- data.frame(perc, pout)

      return(out)

    })
  ) %>% 
  unnest('res')
```

```{r, fig.height = 7, fig.width = 7}
toplo <- grds

p <- ggplot(toplo, aes(x = week1, y = week2, fill = perc)) + 
  geom_tile(color = 'black') + 
  geom_text(aes(label = pout)) + 
  scale_x_continuous('Week', expand = c(0,0), breaks = c(0, 2, 4)) + 
  scale_y_continuous('Week', expand = c(0, 0), breaks= c(2, 4, 6)) + 
  scale_fill_distiller('% diff.', palette = 'Purples', direction = 1) + 
  facet_grid(trt ~ var + species) +
  theme(
    panel.background = element_blank(), 
    strip.background = element_blank(),
    axis.ticks = element_blank()
  ) + 
  labs(
    title = 'Differences in means between experiment time points', 
    subtitle = 'Significant differences are indicated by text'
  )

return(p)
```