---
output: 
  html_document:
    code_folding: hide
css: styles.css
---
  
# Oyster exposure experiments, size and weight quantile regression {.tabset}

Models were created only for individuals showing positive growth 

```{r setup, message = F, warning = F, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(janitor)
library(quantreg)
library(readxl)
library(modelbased)
library(patchwork)
source("R/funcs.R")

trts <- tibble(
  shrtlab = c("8.0C", "8.0A0.2", "7.7C", "7.7A0.2", "7.7A0.5"),
  lngslab = c("8.0 Constant", "8.0 Fluctuating 0.2A", "7.7 Constant", "7.7 Fluctuating 0.2A", "7.7 Fluctuating 0.5A")
)

# consistent response variable terminology names
rsps <- tibble(
  shrtlab = c('size', 'weight'),
  lngslab = c("Final size (cm2)", "Whole weight (g)")
)

# body size, cm2
szdat<- read_csv(here::here('data/raw/finaldata-with-newmissingdata.csv')) %>% 
  clean_names() %>%
  select(week, trt = treatment, jar, id = individual_id, species, final_size = surface_area_cm2_final, initial_size = surface_area_cm2_initial) %>%
  mutate(
    delt_size = final_size - initial_size, 
    init_size = 0,
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, delt_size, init_size) %>% 
  gather('var', 'val', delt_size, init_size) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0, 
      T ~ week
    )
  ) %>% 
  filter(week != 0)

wtdat <- read.csv(here::here('data/raw/Weight_with dead but not multiple_Kelp_4_3.csv'), stringsAsFactors = F) %>% 
  clean_names() %>% 
  # filter(week != 0) %>% 
  filter(species != '') %>% 
  mutate(
    species = gsub('\\s*$', '', species),
    whole_organism_weight = case_when(
      is.na(whole_organism_weight) &  !is.na(shell_weight) & !is.na(tissue_weight) ~ shell_weight + tissue_weight, 
      T ~ whole_organism_weight
    )
  ) %>% 
  filter(!is.na(initial_wetweight) & !is.na(whole_organism_weight)) %>% 
  select(week, trt = treatment, jar = i_jar, id = individual_id, species, initial_weight = initial_wetweight, 
         final_weight = whole_organism_weight) %>% 
  mutate(
    delt_weight = final_weight - initial_weight, 
    init_weight = 0,
  ) %>% 
  filter(week != 0) %>% 
  select(week, trt, jar, id, species, delt_weight, init_weight) %>% 
  gather('var', 'val', delt_weight, init_weight) %>% 
  separate(var, c('period', 'var')) %>% 
  group_by(week, trt, jar, id, species, period, var) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  ungroup %>% 
  filter(!week == 0) %>% 
  mutate(
    week = case_when(
      period == 'init' ~ 0L, 
      T ~ week
    )
  ) %>% 
  filter(week != 0)

# combine size and weight data
allind <- bind_rows(wtdat, szdat) %>% 
  select(-period) %>% 
  mutate(
    trt = factor(trt, levels = trts$shrtlab), 
    var = factor(var, levels = rsps$shrtlab, rsps$lngslab), 
    jar = factor(jar)
  ) %>% 
  mutate(
    direction = sign(val)
  ) %>% 
  filter(direction == 1)

# individual week models
qntplos <- allind %>%  
  group_by(species, var, week) %>% 
  nest %>%
  mutate(
    qtmod = purrr::map(data, function(x){
      
      mod <- rq(val ~ trt, tau = 0.8, data = x)     
      mod <- summary(mod)
      return(mod)
      
    }), 
    qtplo = purrr::pmap(list(data, qtmod, var, week, species), function(data, qtmod, var, week, species){
      
      tomod <- data %>% 
        mutate(
          trt = factor(trt, levels = rev(c(trts$shrtlab)), labels = rev(c( 'Intercept (8.0C)', trts$shrtlab[-1])))
        )
    
      tomodqnts <- tomod %>% 
        group_by(trt) %>% 
        summarise(val = quantile(val, 0.8, na.rm = T))
      
      coeffs <- qtmod$coefficients %>% 
        data.frame %>% 
        rownames_to_column('trt') %>% 
        rename(val = coefficients) %>% 
        rowwise() %>% 
        mutate(
          trt = gsub('^trt', '', trt), 
          trt = factor(trt, levels = rev(c('(Intercept)', trts$shrtlab[-1])), labels = rev(c( 'Intercept (8.0C)', trts$shrtlab[-1]))), 
          pval = ifelse(findInterval(0, c(lower.bd, upper.bd)) == 1, 'ns', 'p < 0.05')
          )
      
      p1 <- ggplot(tomod, aes(y = trt, x = val)) + 
        geom_point(position = position_jitter(height = 0.1), alpha = 0.4) +
        geom_point(data = tomodqnts, col = 'blue', size = 3) + 
        # geom_errorbarh(data = coeffs, aes(xmin = lower.bd, xmax = upper.bd), col = 'red', width = 0.2) + 
        theme_minimal() + 
        theme(
          panel.grid.major.y = element_blank(), 
          panel.grid.minor.y = element_blank(), 
          panel.grid.minor.x = element_blank(), 
          axis.title.y = element_blank()
        ) + 
        labs(
          x = var,
          title = paste(species, '80th percentile model'),
          subtitle = paste0('Week ', week, ', observed data and quantile estimate')
        )
      
      p2 <-  ggplot(coeffs, aes(y = trt, x = val)) + 
        geom_point(data = coeffs, aes(col = pval), size = 3) + 
        geom_errorbarh(data = coeffs, aes(xmin = lower.bd, xmax = upper.bd, col = pval), height = 0.2) +
        scale_colour_manual(values = c('black', 'red')) + 
        geom_vline(xintercept = 0, linetype = 'dashed') +
        theme_minimal() + 
        theme(
          panel.grid.major.y = element_blank(), 
          panel.grid.minor.y = element_blank(), 
          panel.grid.minor.x = element_blank(), 
          axis.title.y = element_blank(), 
          legend.title = element_blank()
        ) + 
        labs(
          x = var,
          subtitle = paste0('Week ', week, ', quantile estimate and CI bounds')
        )
      
      out <- (p1 + p2 + plot_layout(ncol = 2))
      
      return(out)
      
    })
  )

# week by treatment models
qntwkplos <- allind %>%
  mutate(
    week = factor(week, levels = c('2', '4', '6'))
    ) %>% 
  group_by(species, var) %>% 
  nest %>%
  mutate(
    qtmod = purrr::map(data, function(x){

      mod <- rq(val ~ week + trt, tau = 0.8, data = x)
      mod <- summary(mod)
      return(mod)
      
    })
  ) %>% 
  mutate( 
    qtplo = purrr::pmap(list(data, qtmod, var, species), function(data, qtmod, var, species){
      
      coeffs <- qtmod$coefficients %>% 
        data.frame %>% 
        rownames_to_column('trt') %>% 
        rename(val = coefficients) %>% 
        rowwise() %>% 
        mutate(
          trt = gsub('^trt', '', trt), 
          trt = factor(trt,
             levels = c('week6', 'week4', rev(trts$shrtlab[-1]), '(Intercept)'),
             labels = c('week6', 'week4', rev(trts$shrtlab[-1]), 'Intercept (week2, 8.0C)')
             ), 
          pval = ifelse(findInterval(0, c(lower.bd, upper.bd)) == 1, 'ns', 'p < 0.05')
          )

      p <- ggplot(coeffs, aes(y = trt, x = val)) +
        geom_point(aes(col = pval), size = 3) +
        geom_errorbarh(data = coeffs, aes(xmin = lower.bd, xmax = upper.bd, col = pval), height = 0.2) +
        geom_vline(xintercept = 0, linetype = 'dashed') + 
        scale_colour_manual(values = c('black', 'red')) + 
        theme_minimal() +
        theme(
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.minor.x = element_blank(),
          axis.title.y = element_blank(), 
          legend.title = element_blank()
        ) +
        labs(
          x = var,
          title = paste(species, '80th percentile model'),
          subtitle = paste0('Parameter estimates and 95% CI')
        )

      return(p)
      
    })
  )

```

## Whole weight {.tabset .tabset-pills}

### Olympia 

```{r, fig.height = 10, fig.width = 7}
pls <- qntplos %>% 
  filter(var %in% 'Whole weight (g)') %>% 
  filter(species %in% 'Olympia')
pls2 <- qntwkplos %>% 
  filter(var %in% 'Whole weight (g)') %>% 
  filter(species %in% 'Olympia') %>% 
  pull(qtplo) %>% 
  .[[1]]
pl1 <- pls %>% filter(week == 2) %>% pull(qtplo) %>% .[[1]]
pl2 <- pls %>% filter(week == 4) %>% pull(qtplo) %>% .[[1]]
pl3 <- pls %>% filter(week == 6) %>% pull(qtplo) %>% .[[1]]
pl1 / pl2 / pl3 / pls2
```

### Pacific

```{r, fig.height = 10, fig.width = 7}
pls <- qntplos %>% 
  filter(var %in% 'Whole weight (g)') %>% 
  filter(species %in% 'Pacific')
pls2 <- qntwkplos %>% 
  filter(var %in% 'Whole weight (g)') %>% 
  filter(species %in% 'Pacific') %>% 
  pull(qtplo) %>% 
  .[[1]]
pl1 <- pls %>% filter(week == 2) %>% pull(qtplo) %>% .[[1]]
pl2 <- pls %>% filter(week == 4) %>% pull(qtplo) %>% .[[1]]
pl3 <- pls %>% filter(week == 6) %>% pull(qtplo) %>% .[[1]]
pl1 / pl2 / pl3 / pls2
```

## Final size {.tabset .tabset-pills}

### Olympia 

```{r, fig.height = 10, fig.width = 7}
pls <- qntplos %>% 
  filter(var %in% 'Final size (cm2)') %>% 
  filter(species %in% 'Olympia')
pls2 <- qntwkplos %>% 
  filter(var %in% 'Final size (cm2)') %>% 
  filter(species %in% 'Olympia') %>% 
  pull(qtplo) %>% 
  .[[1]]
pl1 <- pls %>% filter(week == 2) %>% pull(qtplo) %>% .[[1]]
pl2 <- pls %>% filter(week == 4) %>% pull(qtplo) %>% .[[1]]
pl3 <- pls %>% filter(week == 6) %>% pull(qtplo) %>% .[[1]]
pl1 / pl2 / pl3 / pls2
```

### Pacific 

```{r, fig.height = 10, fig.width = 7}
pls <- qntplos %>% 
  filter(var %in% 'Final size (cm2)') %>% 
  filter(species %in% 'Pacific')
pls2 <- qntwkplos %>% 
  filter(var %in% 'Final size (cm2)') %>% 
  filter(species %in% 'Pacific') %>% 
  pull(qtplo) %>% 
  .[[1]]
pl1 <- pls %>% filter(week == 2) %>% pull(qtplo) %>% .[[1]]
pl2 <- pls %>% filter(week == 4) %>% pull(qtplo) %>% .[[1]]
pl3 <- pls %>% filter(week == 6) %>% pull(qtplo) %>% .[[1]]
pl1 / pl2 / pl3 / pls2
```

